  name: 同步私有上游仓库

  on:
    schedule:
      - cron: '*/5 * * * *'
    workflow_dispatch:

  jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.PAT_TOKEN }}  # 使用 PAT
            fetch-depth: 0

        - name: 配置 Git 用户信息
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"

        - name: 添加上游仓库（使用 PAT）
          run: |
            git remote add upstream https://${{ secrets.SYNC_TOKEN }}@github.com/JessyTsui/PandaRank.git
            git fetch upstream

        - name: 同步更新
          run: |
            git checkout master
            git merge upstream/master --no-edit
            git push origin master
